### ISSUE TITLE
Data requirements

### ISSUE THREAD

**Issue by yg76cv** [WilkinsYang/CMAF#1]
How can i get the data? Could you give me some way to download these data.

**Comment by GHGluck** [comment]
Thank you for your contribution. Could you open source the dataset? Thank you very much!

**Comment by WilkinsYang** [comment]
The dataset have been updated in the readme, thanks

**Comment by lichengzhou-cmd** [comment]
I did not find the ‘pike’ class in the dataset you provided. Could you please provide the relevant data? Thank you very much.

**Comment by airoue** [comment]
Thank you for your contribution.I attempted to download the dataset using the link provided in the README file, but unfortunately, I encountered a "404 Not Found" error, and the link seems to be inaccessible at the moment.Would it be possible to provide an updated link or alternative access to the dataset?Thank you very much!

**Comment by WilkinsYang** [comment]
The link have been updated in the readme, thanks
